name: Publish review_logs
on:
  push:
    branches:
      - master

defaults:
  run:
    shell: powershell

jobs:
  publish:
    runs-on: ${{ vars.DEFAULT_RUNNER_LABEL }}
    env:
      VENV_NAME: .venv
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Initiate config file
        run: copy config_template.json config.json

      - name: Build config file
        uses: cschleiden/replace-tokens@v1.3
        with:
          tokenPrefix: '$('
          tokenSuffix: ')'
          files: 'config.json'
        env:
          PYTHON_LOG_ROOT: ${{ vars.PYTHON_LOG_ROOT }}

      - name: Clear old files
        run: |
          if (Test-Path "${{ vars.PUBLISH_DIR }}") {
            Remove-Item -Path "${{ vars.PUBLISH_DIR }}" -Recurse -Force
          }

      - name: Deploy files
        run: |
          robocopy ${{ gitea.workspace }} ${{ vars.PUBLISH_DIR }} /MIR /xd .git
          $exitCode = $LASTEXITCODE
          Write-Host "Robocopy exit code: $exitCode"
          if ($exitCode -le 7) {
            exit 0  # consider 0-7 as success per documentation
          } else {
            exit $exitCode
          }

      - name: Create virtual environment
        run: |
          cd "${{ vars.PUBLISH_DIR }}"
          python -m venv $env:VENV_NAME

      - name: Install dependencies
        run: |
          cd "${{ vars.PUBLISH_DIR }}"
          & "${{ vars.PUBLISH_DIR }}\$env:VENV_NAME\Scripts\pip.exe" install -r requirements.txt
